In [1]:
#loading libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("adbc.csv")
df.head()

,Entity,Code,Year,Number of executions (Amnesty International),Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Neoplasms - Sex: Both - Age: All Ages (Number),"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)",Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number),...,Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number),Deaths - Terrorism,Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number),Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number),Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number),Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number),Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number),Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number),Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number),Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,2007,15,2933.0,15925.0,481.0,393.0,2127.0,3657.0,...,2439.0,1199.0,53962.0,4490.0,7222.0,3346.0,6458.0,3437.0,1402.0,450.0
1,Afghanistan,AFG,2008,17,2731.0,16148.0,462.0,255.0,1973.0,3785.0,...,2231.0,1092.0,54051.0,4534.0,7143.0,3316.0,6408.0,3005.0,1424.0,455.0
2,Afghanistan,AFG,2009,0,2460.0,16383.0,448.0,239.0,1852.0,3874.0,...,1998.0,1065.0,53964.0,4597.0,7045.0,3291.0,6358.0,2663.0,1449.0,460.0
3,Afghanistan,AFG,2011,2,2327.0,17094.0,448.0,390.0,1775.0,4170.0,...,1805.0,1525.0,54347.0,4785.0,6916.0,3318.0,6370.0,2365.0,1508.0,473.0
4,Afghanistan,AFG,2012,14,2254.0,17522.0,445.0,94.0,1716.0,4245.0,...,1667.0,3521.0,54868.0,4846.0,6878.0,3353.0,6398.0,2264.0,1544.0,482.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8254 entries, 0 to 8253
Data columns (total 36 columns):
 #   Column                                                                                    Non-Null Count  Dtype
---  ------                                                                                    --------------  -----
 0   Entity                                                                                    8254 non-null   object
 1   Code                                                                                      6206 non-null   object
 2   Year                                                                                      8254 non-null   int64
 3   Number of executions (Amnesty International)                                              267 non-null    object
 4   Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                  8010 non-null   float64
 5   Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                   8010 non-null   float64
 6   Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)              8010 non-null   float64
 7   Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                     8010 non-null   float64
 8   Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                    8010 non-null   float64
 9   Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                      8010 non-null   float64
 10  Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)                                    8010 non-null   float64
 11  Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 12  Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)                                8010 non-null   float64
 13  Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                               8010 non-null   float64
 14  Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 15  Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                8010 non-null   float64
 16  Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 17  Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                       8010 non-null   float64
 18  Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                8010 non-null   float64
 19  Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 20  Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)        8010 non-null   float64
 21  Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                    8010 non-null   float64
 22  Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                   8010 non-null   float64
 23  Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                      8010 non-null   float64
 24  Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                           8010 non-null   float64
 25  Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                  8010 non-null   float64
 26  Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                 8010 non-null   float64
 27  Deaths - Terrorism                                                                        2891 non-null   float64
 28  Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)                     8010 non-null   float64
 29  Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)                      8010 non-null   float64
 30  Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)                8010 non-null   float64
 31  Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)  8010 non-null   float64
 32  Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                          8010 non-null   float64
 33  Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                             8010 non-null   float64
 34  Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)     8010 non-null   float64
 35  Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                         8010 non-null   float64
dtypes: float64(32), int64(1), object(3)
memory usage: 2.3+ MB

# Exploratory Data Analysis

In [4]:
df.isnull().sum() #showing the number of blank/null values in the data frame

Entity                                                                                         0
Code                                                                                        2048
Year                                                                                           0
Number of executions (Amnesty International)                                                7987
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                     244
Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                      244
Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)                 244
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                        244
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                       244
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                         244
Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)                                       244
Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                             244
Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)                                   244
Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                                  244
Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                             244
Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                   244
Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                             244
Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                          244
Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                   244
Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                             244
Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)           244
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                       244
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                      244
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                         244
Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                              244
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                     244
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                    244
Deaths - Terrorism                                                                          5363
Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)                        244
Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)                         244
Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)                   244
Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)     244
Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                             244
Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                                244
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)        244
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                            244
dtype: int64

In [5]:
df1=df.drop('Code',axis='columns') # removing unwanted columns from the data frame
df1.isnull().sum()

Entity                                                                                         0
Year                                                                                           0
Number of executions (Amnesty International)                                                7987
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                     244
Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                      244
Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)                 244
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                        244
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                       244
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                         244
Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)                                       244
Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                             244
Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)                                   244
Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                                  244
Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                             244
Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                   244
Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                             244
Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                          244
Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                   244
Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                             244
Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)           244
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                       244
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                      244
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                         244
Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                              244
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                     244
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                    244
Deaths - Terrorism                                                                          5363
Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)                        244
Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)                         244
Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)                   244
Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)     244
Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                             244
Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                                244
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)        244
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                            244
dtype: int64

In [6]:
# Here we are converting the year to an object and Execution in to float for easy calculation
df2=df1
df2=df2.fillna(0)
df2.head(20)

,Entity,Year,Number of executions (Amnesty International),Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Neoplasms - Sex: Both - Age: All Ages (Number),"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)",Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number),Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number),...,Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number),Deaths - Terrorism,Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number),Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number),Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number),Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number),Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number),Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number),Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number),Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)
0,Afghanistan,2007,15,2933.0,15925.0,481.0,393.0,2127.0,3657.0,148.0,...,2439.0,1199.0,53962.0,4490.0,7222.0,3346.0,6458.0,3437.0,1402.0,450.0
1,Afghanistan,2008,17,2731.0,16148.0,462.0,255.0,1973.0,3785.0,157.0,...,2231.0,1092.0,54051.0,4534.0,7143.0,3316.0,6408.0,3005.0,1424.0,455.0
2,Afghanistan,2009,0,2460.0,16383.0,448.0,239.0,1852.0,3874.0,167.0,...,1998.0,1065.0,53964.0,4597.0,7045.0,3291.0,6358.0,2663.0,1449.0,460.0
3,Afghanistan,2011,2,2327.0,17094.0,448.0,390.0,1775.0,4170.0,184.0,...,1805.0,1525.0,54347.0,4785.0,6916.0,3318.0,6370.0,2365.0,1508.0,473.0
4,Afghanistan,2012,14,2254.0,17522.0,445.0,94.0,1716.0,4245.0,191.0,...,1667.0,3521.0,54868.0,4846.0,6878.0,3353.0,6398.0,2264.0,1544.0,482.0
5,Afghanistan,2013,2,2281.0,18015.0,460.0,143.0,1777.0,4379.0,200.0,...,1651.0,3709.0,55274.0,4945.0,6859.0,3413.0,6476.0,2204.0,1581.0,491.0
6,Afghanistan,2014,6,1935.0,18462.0,463.0,228.0,1757.0,4420.0,213.0,...,1579.0,5414.0,55932.0,5055.0,6851.0,3454.0,6522.0,2134.0,1620.0,502.0
7,Afghanistan,2015,1,1821.0,18876.0,463.0,284.0,1730.0,5039.0,230.0,...,1469.0,6216.0,56875.0,5153.0,6835.0,3492.0,6555.0,2065.0,1652.0,511.0
8,Afghanistan,2016,6,1795.0,19459.0,471.0,388.0,1742.0,5033.0,251.0,...,1416.0,6142.0,57970.0,5296.0,6894.0,3578.0,6673.0,2044.0,1690.0,524.0
9,Afghanistan,1990,0,2159.0,11580.0,323.0,93.0,1370.0,1538.0,34.0,...,2054.0,12.0,44899.0,3709.0,5945.0,2673.0,5005.0,2985.0,1116.0,371.0
10,Afghanistan,1991,0,2218.0,11796.0,332.0,189.0,1391.0,2001.0,41.0,...,2119.0,68.0,45492.0,3724.0,6050.0,2728.0,5120.0,3092.0,1136.0,374.0
11,Afghanistan,1992,0,2475.0,12218.0,360.0,239.0,1514.0,2299.0,48.0,...,2404.0,49.0,46557.0,3776.0,6223.0,2830.0,5335.0,3325.0,1162.0,378.0
12,Afghanistan,1993,0,2812.0,12634.0,396.0,108.0,1687.0,2589.0,56.0,...,2797.0,0.0,47951.0,3862.0,6445.0,2943.0,5568.0,3601.0,1187.0,384.0
13,Afghanistan,1994,0,3027.0,12914.0,420.0,211.0,1809.0,2849.0,63.0,...,3038.0,22.0,49308.0,3932.0,6664.0,3027.0,5739.0,3816.0,1211.0,391.0
14,Afghanistan,1995,0,3102.0,13106.0,434.0,175.0,1881.0,2969.0,71.0,...,3087.0,5.0,50158.0,3974.0,6823.0,3076.0,5843.0,3946.0,1225.0,394.0
15,Afghanistan,1996,0,3193.0,13335.0,450.0,175.0,1969.0,3331.0,78.0,...,3130.0,31.0,51125.0,4041.0,7000.0,3133.0,5966.0,4098.0,1239.0,398.0
16,Afghanistan,1997,0,3303.0,13572.0,469.0,240.0,2078.0,3028.0,84.0,...,3203.0,4.0,52039.0,4094.0,7168.0,3200.0,6096.0,4252.0,1253.0,402.0
17,Afghanistan,1998,0,3281.0,13695.0,472.0,563.0,2098.0,3098.0,89.0,...,3145.0,8.0,52720.0,4120.0,7287.0,3231.0,6154.0,4310.0,1267.0,405.0
18,Afghanistan,1999,0,3200.0,13811.0,470.0,468.0,2084.0,2917.0,93.0,...,3068.0,39.0,53413.0,4150.0,7400.0,3247.0,6182.0,4332.0,1281.0,409.0
19,Afghanistan,2000,0,3105.0,13977.0,465.0,263.0,2048.0,2871.0,97.0,...,3013.0,38.0,53919.0,4182.0,7471.0,3249.0,6206.0,4334.0,1291.0,416.0

In [7]:
df2.isnull().sum()

Entity                                                                                      0
Year                                                                                        0
Number of executions (Amnesty International)                                                0
Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                    0
Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                     0
Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)                0
Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                       0
Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                      0
Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                        0
Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)                                      0
Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                            0
Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)                                  0
Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                                 0
Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                            0
Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                  0
Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                            0
Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                         0
Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                  0
Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                            0
Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)          0
Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                      0
Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                     0
Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                        0
Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                             0
Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                    0
Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                   0
Deaths - Terrorism                                                                          0
Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)                       0
Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)                        0
Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)                  0
Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)    0
Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                            0
Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                               0
Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)       0
Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                           0
dtype: int64

In [8]:
# Here we are converting the year to an object and Execution in to float for easy calculation
df2['Year'] = df['Year'].apply(str)
df2['Number of executions (Amnesty International)'] = pd.to_numeric(df2['Number of executions (Amnesty International)'],errors = 'coerce')
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8254 entries, 0 to 8253
Data columns (total 35 columns):
 #   Column                                                                                    Non-Null Count  Dtype
---  ------                                                                                    --------------  -----
 0   Entity                                                                                    8254 non-null   object
 1   Year                                                                                      8254 non-null   object
 2   Number of executions (Amnesty International)                                              8237 non-null   float64
 3   Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                  8254 non-null   float64
 4   Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                   8254 non-null   float64
 5   Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)              8254 non-null   float64
 6   Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                     8254 non-null   float64
 7   Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                    8254 non-null   float64
 8   Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                      8254 non-null   float64
 9   Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)                                    8254 non-null   float64
 10  Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 11  Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)                                8254 non-null   float64
 12  Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                               8254 non-null   float64
 13  Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 14  Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                8254 non-null   float64
 15  Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 16  Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                       8254 non-null   float64
 17  Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                8254 non-null   float64
 18  Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 19  Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)        8254 non-null   float64
 20  Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                    8254 non-null   float64
 21  Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                   8254 non-null   float64
 22  Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                      8254 non-null   float64
 23  Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                           8254 non-null   float64
 24  Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                  8254 non-null   float64
 25  Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                 8254 non-null   float64
 26  Deaths - Terrorism                                                                        8254 non-null   float64
 27  Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)                     8254 non-null   float64
 28  Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)                      8254 non-null   float64
 29  Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)                8254 non-null   float64
 30  Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)  8254 non-null   float64
 31  Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 32  Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                             8254 non-null   float64
 33  Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)     8254 non-null   float64
 34  Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                         8254 non-null   float64
dtypes: float64(33), object(2)
memory usage: 2.2+ MB
None

In [9]:
num_col = df2._get_numeric_data().columns.tolist() #identifying the numberic columns 
print(num_col)

['Number of executions (Amnesty International)', 'Deaths - Meningitis - Sex: Both - Age: All Ages (Number)', 'Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)', 'Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)', 'Deaths - Malaria - Sex: Both - Age: All Ages (Number)', 'Deaths - Drowning - Sex: Both - Age: All Ages (Number)', 'Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)', 'Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)', 'Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)', 'Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)', 'Deaths - Road injuries - Sex: Both - Age: All Ages (Number)', 'Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)', 'Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)', 'Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)', 'Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)', 'Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)', 'Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)', 'Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)', 'Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)', 'Deaths - Self-harm - Sex: Both - Age: All Ages (Number)', 'Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)', 'Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)', 'Deaths - Poisonings - Sex: Both - Age: All Ages (Number)', 'Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)', 'Deaths - Terrorism', 'Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)', 'Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)', 'Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)', 'Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)', 'Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)', 'Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)', "Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)", "Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)"]

In [10]:
# here we are trying to find ther totla 
df2['Total_Deaths_Per_Year'] = df2.sum(axis = 1)
#df2.loc['Total_Deaths']= df2.sum(numeric_only=True, axis=0)
df2 = df2.replace(np.nan, '', regex=True)
df2.head()

C:\Users\abhis\AppData\Local\Temp/ipykernel_23164/739756805.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df2['Total_Deaths_Per_Year'] = df2.sum(axis = 1)

,Entity,Year,Number of executions (Amnesty International),Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Neoplasms - Sex: Both - Age: All Ages (Number),"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)",Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number),Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number),...,Deaths - Terrorism,Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number),Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number),Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number),Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number),Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number),Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number),Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number),Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number),Total_Deaths_Per_Year
0,Afghanistan,2007,15.0,2933.0,15925.0,481.0,393.0,2127.0,3657.0,148.0,...,1199.0,53962.0,4490.0,7222.0,3346.0,6458.0,3437.0,1402.0,450.0,204812.0
1,Afghanistan,2008,17.0,2731.0,16148.0,462.0,255.0,1973.0,3785.0,157.0,...,1092.0,54051.0,4534.0,7143.0,3316.0,6408.0,3005.0,1424.0,455.0,200226.0
2,Afghanistan,2009,0.0,2460.0,16383.0,448.0,239.0,1852.0,3874.0,167.0,...,1065.0,53964.0,4597.0,7045.0,3291.0,6358.0,2663.0,1449.0,460.0,195927.0
3,Afghanistan,2011,2.0,2327.0,17094.0,448.0,390.0,1775.0,4170.0,184.0,...,1525.0,54347.0,4785.0,6916.0,3318.0,6370.0,2365.0,1508.0,473.0,196561.0
4,Afghanistan,2012,14.0,2254.0,17522.0,445.0,94.0,1716.0,4245.0,191.0,...,3521.0,54868.0,4846.0,6878.0,3353.0,6398.0,2264.0,1544.0,482.0,200377.0

In [11]:
# Here we are converting the year to an object and Execution in to float for easy calculation
df2['Year'] = df['Year'].apply(float)
df2['Number of executions (Amnesty International)'] = pd.to_numeric(df2['Number of executions (Amnesty International)'],errors = 'coerce')
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8254 entries, 0 to 8253
Data columns (total 36 columns):
 #   Column                                                                                    Non-Null Count  Dtype
---  ------                                                                                    --------------  -----
 0   Entity                                                                                    8254 non-null   object
 1   Year                                                                                      8254 non-null   float64
 2   Number of executions (Amnesty International)                                              8237 non-null   float64
 3   Deaths - Meningitis - Sex: Both - Age: All Ages (Number)                                  8254 non-null   float64
 4   Deaths - Neoplasms - Sex: Both - Age: All Ages (Number)                                   8254 non-null   float64
 5   Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)              8254 non-null   float64
 6   Deaths - Malaria - Sex: Both - Age: All Ages (Number)                                     8254 non-null   float64
 7   Deaths - Drowning - Sex: Both - Age: All Ages (Number)                                    8254 non-null   float64
 8   Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number)                      8254 non-null   float64
 9   Deaths - HIV/AIDS - Sex: Both - Age: All Ages (Number)                                    8254 non-null   float64
 10  Deaths - Drug use disorders - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 11  Deaths - Tuberculosis - Sex: Both - Age: All Ages (Number)                                8254 non-null   float64
 12  Deaths - Road injuries - Sex: Both - Age: All Ages (Number)                               8254 non-null   float64
 13  Deaths - Maternal disorders - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 14  Deaths - Lower respiratory infections - Sex: Both - Age: All Ages (Number)                8254 non-null   float64
 15  Deaths - Neonatal disorders - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 16  Deaths - Alcohol use disorders - Sex: Both - Age: All Ages (Number)                       8254 non-null   float64
 17  Deaths - Exposure to forces of nature - Sex: Both - Age: All Ages (Number)                8254 non-null   float64
 18  Deaths - Diarrheal diseases - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 19  Deaths - Environmental heat and cold exposure - Sex: Both - Age: All Ages (Number)        8254 non-null   float64
 20  Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number)                    8254 non-null   float64
 21  Deaths - Self-harm - Sex: Both - Age: All Ages (Number)                                   8254 non-null   float64
 22  Deaths - Conflict and terrorism - Sex: Both - Age: All Ages (Number)                      8254 non-null   float64
 23  Deaths - Diabetes mellitus - Sex: Both - Age: All Ages (Number)                           8254 non-null   float64
 24  Deaths - Poisonings - Sex: Both - Age: All Ages (Number)                                  8254 non-null   float64
 25  Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number)                 8254 non-null   float64
 26  Deaths - Terrorism                                                                        8254 non-null   float64
 27  Deaths - Cardiovascular diseases - Sex: Both - Age: All Ages (Number)                     8254 non-null   float64
 28  Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number)                      8254 non-null   float64
 29  Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number)                8254 non-null   float64
 30  Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number)  8254 non-null   float64
 31  Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number)                          8254 non-null   float64
 32  Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)                             8254 non-null   float64
 33  Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number)     8254 non-null   float64
 34  Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number)                         8254 non-null   float64
 35  Total_Deaths_Per_Year                                                                     8254 non-null   float64
dtypes: float64(35), object(1)
memory usage: 2.3+ MB
None